Repository SwevenSoftware/BlockCOVID-server, pull requests merged in 2021-04, with the labels that each got.

#81 Feature/pdf reports
  build.gradle
  codecov.yml
  src/main/java/it/sweven/blockcovid/documents/PdfReport.java
  src/main/java/it/sweven/blockcovid/entities/room/Room.java
  src/main/java/it/sweven/blockcovid/routers/admin/AdminCleanerReportRouter.java
  src/main/java/it/sweven/blockcovid/services/DocumentService.java
  src/test/java/it/sweven/blockcovid/documents/PdfReportTest.java
  src/test/java/it/sweven/blockcovid/entities/room/RoomTest.java
  src/test/java/it/sweven/blockcovid/routers/admin/AdminCleanerReportRouterTest.java
  src/test/java/it/sweven/blockcovid/services/DocumentServiceTest.java
Labels: enhancement

#83 Feature/https fix
  README.md
  src/main/java/it/sweven/blockcovid/configurations/WebSecurityConfiguration.java
  src/main/java/it/sweven/blockcovid/controllers/admin/AdminCleanerReportController.java
  src/main/resources/application.properties
Labels: enhancement, refactor

#93 Feature/view desk state
  src/main/java/it/sweven/blockcovid/reservations/assemblers/ReservationAssembler.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/GetDeskStateAtTimeController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/NewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/dto/DeskAvailability.java
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/reservations/exceptions/NoNextReservation.java
  src/main/java/it/sweven/blockcovid/reservations/repositories/ReservationRepository.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/DeleteDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ModifyDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/NewDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ViewDeskStateController.java
  src/main/java/it/sweven/blockcovid/rooms/dto/DeskWithRoomName.java
  src/main/java/it/sweven/blockcovid/rooms/repositories/RoomRepository.java
  src/main/java/it/sweven/blockcovid/rooms/services/DeskService.java
  src/main/resources/application.properties
  src/test/java/it/sweven/blockcovid/reservations/controllers/GetDeskStateAtTimeControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/DeleteDeskControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ModifyDeskControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/NewDeskControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ViewDeskStateControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/services/DeskServiceTest.java
Labels: enhancement, refactor

#94 Modify and delete reservations
  src/main/java/it/sweven/blockcovid/reservations/controllers/DeleteReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ModifyReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/exceptions/NoSuchReservation.java
  src/main/java/it/sweven/blockcovid/reservations/repositories/ReservationRepository.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/DeleteReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/ModifyReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: enhancement

#104 Display security info in Swagger UI
  src/main/java/it/sweven/blockcovid/blockchain/controllers/ReportsController.java
  src/main/java/it/sweven/blockcovid/configurations/OpenAPIConfiguration.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/dto/ReservationInfo.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/RoomsController.java
  src/main/java/it/sweven/blockcovid/users/controllers/AccountInfoController.java
  src/main/java/it/sweven/blockcovid/users/controllers/ModifyPasswordController.java
  src/main/java/it/sweven/blockcovid/users/controllers/UsersController.java
Labels: documentation

#106 Feature/configuration and bugfixes
  .env
  Dockerfile
  README.md
  docker-compose.yml
  src/main/java/it/sweven/blockcovid/configurations/BlockchainConfiguration.java
  src/main/java/it/sweven/blockcovid/configurations/WebSecurityConfiguration.java
  src/main/resources/application.properties
Labels: bug

#107 Reservation checks
  src/main/java/it/sweven/blockcovid/configurations/WebSecurityConfiguration.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/NewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/dto/ReservationInfo.java
  src/main/java/it/sweven/blockcovid/reservations/exceptions/BadTimeIntervals.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/main/java/it/sweven/blockcovid/rooms/entities/Room.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/NewReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/dto/ReservationInfoTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
  src/test/java/it/sweven/blockcovid/rooms/entities/RoomTest.java
Labels: bug, refactor

#111 Feature/checks reservations
  src/main/java/it/sweven/blockcovid/reservations/controllers/NewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/NewReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: enhancement

#112 logout controller, expiration is checked when authenticating
  src/main/java/it/sweven/blockcovid/users/controllers/LogoutController.java
  src/main/java/it/sweven/blockcovid/users/repositories/TokenRepository.java
  src/main/java/it/sweven/blockcovid/users/security/TokenAuthenticationProvider.java
  src/main/java/it/sweven/blockcovid/users/services/TokenService.java
  src/test/java/it/sweven/blockcovid/users/controllers/LogoutControllerTest.java
  src/test/java/it/sweven/blockcovid/users/security/TokenAuthenticationProviderTest.java
  src/test/java/it/sweven/blockcovid/users/services/TokenServiceTest.java
Labels: bug

#113 Show room's name while retriving reservations
  src/main/java/it/sweven/blockcovid/configurations/LocalDateTimeConfiguration.java
  src/main/java/it/sweven/blockcovid/reservations/assemblers/ReservationWithRoomAssembler.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/DeleteReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ModifyReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/NewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ViewAllReservationsController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalReservationsController.java
  src/main/java/it/sweven/blockcovid/reservations/dto/ReservationWithRoom.java
  src/main/java/it/sweven/blockcovid/reservations/entities/ReservationBuilder.java
  src/main/java/it/sweven/blockcovid/reservations/repositories/ReservationRepository.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/reservations/assemblers/ReservationWithRoomAssemblerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/DeleteReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/GetDeskStateAtTimeControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/ModifyReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/NewReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/ViewAllReservationsControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalReservationsControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationBuilderTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ListRoomsControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ViewRoomControllerTest.java
Labels: enhancement, refactor

#119 moved clash logic to reservations
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/reservations/repositories/ReservationRepository.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/main/java/it/sweven/blockcovid/rooms/services/RoomService.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: refactor

#120 Return desk availability within any time interval with room view and list rooms
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/rooms/assemblers/RoomAssembler.java
  src/main/java/it/sweven/blockcovid/rooms/assemblers/RoomWithDesksAssembler.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ListRoomsController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ViewRoomController.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ListRoomsControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ViewRoomControllerTest.java
Labels: refactor

#122 reservations now have a realStart && end attribute, closes #115
  src/main/java/it/sweven/blockcovid/reservations/controllers/NewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/reservations/entities/ReservationBuilder.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/NewReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationBuilderTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: enhancement

#124 fix error 415 media type on GET requests
  src/main/java/it/sweven/blockcovid/users/controllers/AccountInfoController.java
  src/main/java/it/sweven/blockcovid/users/controllers/ListUsersController.java
Labels: refactor

#125 Feature/report usage
  .env
  README.md
  docker-compose.yml
  src/main/java/it/sweven/blockcovid/blockchain/controllers/BlockchainCleanerController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/BlockchainUsageController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/CleanerReportController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/UsageReportController.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentService.java
  src/main/java/it/sweven/blockcovid/reservations/dto/ReservationWithRoom.java
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/reservations/entities/ReservationBuilder.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/BlockchainCleanerControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/BlockchainUsageControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/CleanerReportControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/UsageReportControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/services/DocumentServiceTest.java
  src/test/java/it/sweven/blockcovid/reservations/dto/ReservationWithRoomTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationBuilderTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationTest.java
Labels: enhancement

#123 Feature/start reservaiton controller
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartNewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalDeskReservationsController.java
  src/main/java/it/sweven/blockcovid/reservations/dto/ReservationInfo.java
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/reservations/exceptions/StartingTooEarly.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/StartNewReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/StartReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalDeskReservationsControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationBuilderTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: enhancement

#126 Feature/blockchain revision
  .env
  README.md
  docker-compose.yml
  src/main/java/it/sweven/blockcovid/blockchain/controllers/AutomaticCleanerController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/AutomaticUsageController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/BlockchainCleanerController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/BlockchainUsageController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/CleanerReportController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/UsageReportController.java
  src/main/java/it/sweven/blockcovid/blockchain/entities/DeploymentInformation.java
  src/main/java/it/sweven/blockcovid/blockchain/exceptions/ContractNotDeployed.java
  src/main/java/it/sweven/blockcovid/blockchain/exceptions/InvalidNetworkException.java
  src/main/java/it/sweven/blockcovid/blockchain/repositories/DeploymentInformationRepository.java
  src/main/java/it/sweven/blockcovid/blockchain/repositories/DocumentContractRepository.java
  src/main/java/it/sweven/blockcovid/blockchain/services/BlockchainService.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DeploymentInformationService.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DeploymentService.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentContractService.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentService.java
  src/main/java/it/sweven/blockcovid/blockchain/services/SignRegistrationService.java
  src/main/java/it/sweven/blockcovid/configurations/BlockchainConfiguration.java
  src/main/java/it/sweven/blockcovid/configurations/BlockchainConnectionConfiguration.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/AutomaticCleanerControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/AutomaticUsageControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/BlockchainCleanerControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/BlockchainUsageControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/CleanerReportControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/UsageReportControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/services/BlockchainServiceTest.java
  src/test/java/it/sweven/blockcovid/blockchain/services/DeploymentInformationServiceTest.java
  src/test/java/it/sweven/blockcovid/blockchain/services/SignRegistrationServiceTest.java
Labels: enhancement, refactor

#128 End usage controller
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentService.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/EndReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartNewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/dto/EndUsageInfo.java
  src/main/java/it/sweven/blockcovid/reservations/dto/ReservationWithRoom.java
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/reservations/exceptions/AlreadyEnded.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/blockchain/services/DocumentServiceTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/EndReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/StartReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/dto/ReservationWithRoomTest.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: enhancement, refactor

#127 Fix report overflow
  src/main/java/it/sweven/blockcovid/blockchain/documents/PdfReport.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentService.java
  src/test/java/it/sweven/blockcovid/blockchain/documents/PdfReportTest.java
  src/test/java/it/sweven/blockcovid/blockchain/services/DocumentServiceTest.java
Labels: enhancement, refactor

#129 added swagger annotations
  src/main/java/it/sweven/blockcovid/blockchain/controllers/UsageReportController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/GetDeskStateAtTimeController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartNewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartReservationController.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/StartNewReservationControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/StartReservationControllerTest.java
Labels: documentation

#132 Distinguish report types based on their filename
  src/main/java/it/sweven/blockcovid/blockchain/documents/ReportType.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentService.java
  src/test/java/it/sweven/blockcovid/blockchain/services/DocumentServiceTest.java
Labels: enhancement

#133 Feature/list report controller
  src/main/java/it/sweven/blockcovid/blockchain/assemblers/ReportInformationAssembler.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/ListReportsController.java
  src/main/java/it/sweven/blockcovid/blockchain/dto/ReportInformation.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentService.java
  src/test/java/it/sweven/blockcovid/blockchain/assemblers/ReportInformationAssemblerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/ListReportsControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/dto/ReportInformationTest.java
  src/test/java/it/sweven/blockcovid/blockchain/services/DocumentServiceTest.java
Labels: enhancement

#134 Retrieve single report
  src/main/java/it/sweven/blockcovid/blockchain/controllers/GetReportController.java
  src/main/java/it/sweven/blockcovid/blockchain/services/DocumentService.java
  src/test/java/it/sweven/blockcovid/blockchain/controllers/GetReportControllerTest.java
  src/test/java/it/sweven/blockcovid/blockchain/services/DocumentServiceTest.java
Labels: enhancement

#135 fixed personal reservation view
  src/main/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalDeskReservationsController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalReservationsController.java
  src/main/java/it/sweven/blockcovid/reservations/repositories/ReservationRepository.java
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalDeskReservationsControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/controllers/ViewPersonalReservationsControllerTest.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: bug

#136 Display desk room name each time a desk is returned
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/DeleteDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ModifyDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/NewDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ViewDeskStateController.java
  src/main/java/it/sweven/blockcovid/rooms/dto/DeskWithRoomName.java
  src/main/java/it/sweven/blockcovid/rooms/entities/Desk.java
  src/main/java/it/sweven/blockcovid/rooms/services/DeskService.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/DeleteDeskControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ListRoomsControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ModifyDeskControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/NewDeskControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ViewDeskStateControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ViewRoomControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/services/DeskServiceTest.java
Labels: bug
