Repository SwevenSoftware/BlockCOVID-server, pull requests merged in 2021-03, with the labels that each got.

#31 Feature/docker refactor
  Dockerfile
  README.md
  docker-compose.yml
  src/main/resources/application.properties
Labels: refactor

#45 Unit tests for services
  src/test/java/it/sweven/blockcovid/services/TokenServiceTest.java
  src/test/java/it/sweven/blockcovid/services/UUIDAuthenticationServiceTest.java
  src/test/java/it/sweven/blockcovid/services/UserRegistrationServiceTest.java
  src/test/java/it/sweven/blockcovid/services/UserServiceTest.java
Labels: testing

#46 added badges on the README
  README.md
Labels: documentation

#47 explicitly moved initDB after the initialization of beans
  src/main/java/it/sweven/blockcovid/services/UserService.java
Labels: refactor

#49 Improved routers code-coverage
  src/test/java/it/sweven/blockcovid/routers/AdminRouterTest.java
  src/test/java/it/sweven/blockcovid/routers/LoginRouterTest.java
Labels: testing

#48 Added initDB tests
  src/test/java/it/sweven/blockcovid/services/UserServiceTest.java
Labels: testing

#50 Feature/entity tests
  src/main/java/it/sweven/blockcovid/entities/user/User.java
  src/main/java/it/sweven/blockcovid/entities/user/UserBuilder.java
  src/test/java/it/sweven/blockcovid/entities/user/AuthorityTest.java
  src/test/java/it/sweven/blockcovid/entities/user/TokenTest.java
  src/test/java/it/sweven/blockcovid/entities/user/UserBuilderTest.java
  src/test/java/it/sweven/blockcovid/entities/user/UserTest.java
Labels: testing

#51 Security unit tests
  src/test/java/it/sweven/blockcovid/security/TokenAuthenticationFilterTest.java
  src/test/java/it/sweven/blockcovid/security/TokenAuthenticationProviderTest.java
Labels: testing

#52 Removed unused features
  README.md
  build.gradle
  docker-compose.yml
  pre-commit.sh
  src/main/java/it/sweven/blockcovid/contracts/Document.java
  src/main/java/it/sweven/blockcovid/documents/PdfReport.java
  src/main/java/it/sweven/blockcovid/entities/Reservation.java
  src/main/java/it/sweven/blockcovid/repositories/ReservationRepository.java
  src/main/java/it/sweven/blockcovid/services/blockchain/EthereumConfiguration.java
  src/main/java/it/sweven/blockcovid/services/blockchain/EthereumRunner.java
  src/main/resources/templates/index.html
Labels: refactor

#64 Room and desk entities
  .github/workflows/coverage-server.yml
  build.gradle
  lombok.config
  src/main/java/it/sweven/blockcovid/configurations/MongoConfiguration.java
  src/main/java/it/sweven/blockcovid/entities/room/Desk.java
  src/main/java/it/sweven/blockcovid/entities/room/Room.java
  src/test/java/it/sweven/blockcovid/entities/room/DeskTest.java
  src/test/java/it/sweven/blockcovid/entities/room/RoomTest.java
Labels: enhancement

#66 Feature/view room
  src/main/java/it/sweven/blockcovid/assemblers/RoomAssembler.java
  src/main/java/it/sweven/blockcovid/exceptions/RoomNotFoundException.java
  src/main/java/it/sweven/blockcovid/repositories/RoomRepository.java
  src/main/java/it/sweven/blockcovid/routers/RoomRouter.java
  src/main/java/it/sweven/blockcovid/services/RoomService.java
  src/test/java/it/sweven/blockcovid/assemblers/RoomAssemblerTest.java
  src/test/java/it/sweven/blockcovid/routers/RoomRouterTest.java
  src/test/java/it/sweven/blockcovid/services/RoomServiceTest.java
Labels: enhancement

#70 Create new Desk
  src/main/java/it/sweven/blockcovid/assemblers/DeskAssembler.java
  src/main/java/it/sweven/blockcovid/dto/DeskInfo.java
  src/main/java/it/sweven/blockcovid/dto/DeskWithRoomName.java
  src/main/java/it/sweven/blockcovid/entities/room/Desk.java
  src/main/java/it/sweven/blockcovid/exceptions/DeskNotAvailable.java
  src/main/java/it/sweven/blockcovid/repositories/DeskRepository.java
  src/main/java/it/sweven/blockcovid/routers/AdminRouter.java
  src/main/java/it/sweven/blockcovid/services/DeskService.java
  src/test/java/it/sweven/blockcovid/assemblers/DeskAssemblerTest.java
  src/test/java/it/sweven/blockcovid/entities/room/DeskTest.java
  src/test/java/it/sweven/blockcovid/exceptions/DeskNotAvailableTest.java
  src/test/java/it/sweven/blockcovid/routers/AdminRouterTest.java
  src/test/java/it/sweven/blockcovid/services/DeskServiceTest.java
Labels: enhancement

#72 List associated desks when listing rooms
  src/main/java/it/sweven/blockcovid/assemblers/RoomAssembler.java
  src/main/java/it/sweven/blockcovid/dto/RoomWithDesks.java
  src/main/java/it/sweven/blockcovid/repositories/DeskRepository.java
  src/main/java/it/sweven/blockcovid/routers/AdminRouter.java
  src/main/java/it/sweven/blockcovid/routers/RoomRouter.java
  src/main/java/it/sweven/blockcovid/services/DeskService.java
  src/test/java/it/sweven/blockcovid/assemblers/RoomAssemblerTest.java
  src/test/java/it/sweven/blockcovid/routers/RoomRouterTest.java
  src/test/java/it/sweven/blockcovid/services/DeskServiceTest.java
Labels: enhancement

#75 admin can delete a room by her name, closes #57
  src/main/java/it/sweven/blockcovid/repositories/DeskRepository.java
  src/main/java/it/sweven/blockcovid/repositories/RoomRepository.java
  src/main/java/it/sweven/blockcovid/routers/admin/AdminDeleteRoomRouter.java
  src/main/java/it/sweven/blockcovid/services/RoomService.java
  src/test/java/it/sweven/blockcovid/routers/admin/AdminDeleteRoomRouterTest.java
  src/test/java/it/sweven/blockcovid/services/RoomServiceTest.java
Labels: enhancement

#74 Cleaners can mark a room and all desks inside as clean, closes #58
  src/main/java/it/sweven/blockcovid/entities/room/Desk.java
  src/main/java/it/sweven/blockcovid/entities/room/Room.java
  src/main/java/it/sweven/blockcovid/entities/room/Status.java
  src/main/java/it/sweven/blockcovid/routers/cleaner/CleanerMarkRoomAsCleanRouter.java
  src/main/java/it/sweven/blockcovid/routers/cleaner/CleanerRouter.java
  src/main/java/it/sweven/blockcovid/services/RoomService.java
  src/test/java/it/sweven/blockcovid/routers/cleaner/CleanerMarkRoomAsCleanRouterTest.java
  src/test/java/it/sweven/blockcovid/services/RoomServiceTest.java
Labels: enhancement

#76 Admin can modify a room with put request, closes #56
  src/main/java/it/sweven/blockcovid/routers/admin/AdminModifyRoomRouter.java
  src/main/java/it/sweven/blockcovid/services/RoomService.java
  src/test/java/it/sweven/blockcovid/routers/admin/AdminModifyRoomRouterTest.java
  src/test/java/it/sweven/blockcovid/services/RoomServiceTest.java
Labels: enhancement

#79 Fix swagger grouping
  src/main/java/it/sweven/blockcovid/configurations/ApiDocumentationConfiguration.java
  src/main/java/it/sweven/blockcovid/routers/LoginRouter.java
  src/main/java/it/sweven/blockcovid/routers/RoomRouter.java
  src/main/java/it/sweven/blockcovid/routers/admin/AdminRouter.java
  src/main/java/it/sweven/blockcovid/routers/user/UserRouter.java
  src/main/resources/application.properties
Labels: documentation

#78 Feature/user checks
  build.gradle
  src/main/java/it/sweven/blockcovid/dto/CredentialChangeRequestForm.java
  src/main/java/it/sweven/blockcovid/dto/Credentials.java
  src/main/java/it/sweven/blockcovid/dto/CredentialsWithAuthorities.java
  src/main/java/it/sweven/blockcovid/dto/TokenWithAuthorities.java
  src/main/java/it/sweven/blockcovid/entities/user/UserBuilder.java
  src/main/java/it/sweven/blockcovid/routers/LoginRouter.java
  src/main/java/it/sweven/blockcovid/routers/admin/AdminRegistrationRouter.java
  src/main/java/it/sweven/blockcovid/services/UserRegistrationService.java
  src/test/java/it/sweven/blockcovid/services/UserRegistrationServiceTest.java
Labels: enhancement

#77 admin can now delete a desk inside a room, closes #69
  src/main/java/it/sweven/blockcovid/exceptions/DeskNotFoundException.java
  src/main/java/it/sweven/blockcovid/repositories/DeskRepository.java
  src/main/java/it/sweven/blockcovid/routers/admin/AdminDeleteDeskRouter.java
  src/main/java/it/sweven/blockcovid/services/DeskService.java
  src/test/java/it/sweven/blockcovid/routers/admin/AdminDeleteDeskRouterTest.java
  src/test/java/it/sweven/blockcovid/services/DeskServiceTest.java
Labels: enhancement

#80 Room construction moved to builder, desks are now identified by x/y axis
  src/main/java/it/sweven/blockcovid/dto/DeskInfo.java
  src/main/java/it/sweven/blockcovid/dto/DeskWithRoomName.java
  src/main/java/it/sweven/blockcovid/entities/room/Desk.java
  src/main/java/it/sweven/blockcovid/entities/room/Room.java
  src/main/java/it/sweven/blockcovid/entities/room/RoomBuilder.java
  src/main/java/it/sweven/blockcovid/repositories/DeskRepository.java
  src/main/java/it/sweven/blockcovid/routers/RoomRouter.java
  src/main/java/it/sweven/blockcovid/routers/admin/AdminDeleteDeskRouter.java
  src/main/java/it/sweven/blockcovid/routers/admin/AdminNewDeskRouter.java
  src/main/java/it/sweven/blockcovid/services/DeskService.java
  src/main/java/it/sweven/blockcovid/services/RoomService.java
  src/test/java/it/sweven/blockcovid/entities/room/DeskTest.java
  src/test/java/it/sweven/blockcovid/entities/room/RoomBuilderTest.java
  src/test/java/it/sweven/blockcovid/entities/room/RoomTest.java
  src/test/java/it/sweven/blockcovid/routers/RoomRouterTest.java
  src/test/java/it/sweven/blockcovid/routers/admin/AdminDeleteDeskRouterTest.java
  src/test/java/it/sweven/blockcovid/routers/admin/AdminModifyRoomRouterTest.java
  src/test/java/it/sweven/blockcovid/routers/admin/AdminNewDeskRouterTest.java
  src/test/java/it/sweven/blockcovid/services/DeskServiceTest.java
Labels: refactor
