Repository SwevenSoftware/BlockCOVID-server, pull requests merged in 2021-05, with the labels that each got.

#137 fix clash with real usage
  src/main/java/it/sweven/blockcovid/reservations/entities/Reservation.java
  src/test/java/it/sweven/blockcovid/reservations/entities/ReservationTest.java
Labels: bug

#138 Set room as dirty on reservation start
  src/main/java/it/sweven/blockcovid/reservations/servicies/ReservationService.java
  src/test/java/it/sweven/blockcovid/reservations/servicies/ReservationServiceTest.java
Labels: bug

#140 Feature/unique room name
  src/main/java/it/sweven/blockcovid/rooms/controllers/ModifyRoomController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/NewRoomController.java
  src/main/java/it/sweven/blockcovid/rooms/exceptions/RoomNameNotAvailable.java
  src/main/java/it/sweven/blockcovid/rooms/services/RoomService.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/MarkRoomAsCleanControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/ModifyRoomControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/controllers/NewRoomControllerTest.java
  src/test/java/it/sweven/blockcovid/rooms/services/RoomServiceTest.java
Labels: bug

#141 Feature/loggers
  src/main/java/it/sweven/blockcovid/blockchain/controllers/AutomaticCleanerController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/AutomaticUsageController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/CleanerReportController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/GetReportController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/ListReportsController.java
  src/main/java/it/sweven/blockcovid/blockchain/controllers/UsageReportController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/EndReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/ModifyReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/NewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartNewReservationController.java
  src/main/java/it/sweven/blockcovid/reservations/controllers/StartReservationController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/MarkRoomAsCleanController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ModifyDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ModifyRoomController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/NewDeskController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/NewRoomController.java
  src/main/java/it/sweven/blockcovid/rooms/controllers/ViewRoomController.java
  src/main/java/it/sweven/blockcovid/users/controllers/DeleteUserController.java
  src/main/java/it/sweven/blockcovid/users/controllers/LoginController.java
  src/main/java/it/sweven/blockcovid/users/controllers/ModifyPasswordController.java
  src/main/java/it/sweven/blockcovid/users/controllers/ModifyUserController.java
  src/main/java/it/sweven/blockcovid/users/controllers/RegistrationController.java
Labels: enhancement

#144 Spotless badge
  README.md
Labels: documentation

#146 Fix login errors when username not found
  src/main/java/it/sweven/blockcovid/users/controllers/LoginController.java
  src/test/java/it/sweven/blockcovid/users/controllers/LoginControllerTest.java
Labels: bug
